In [1]:
import os
import json
import pandas as pd
from scipy import stats

In [2]:
filenames = os.listdir('stats/')
filenames

['gen.json',
 'gorky.json',
 'gpt2.json',
 'gpt3.json',
 'metrics.csv',
 'news_dp.json',
 'science.json',
 'str_1_2.json',
 'str_1_6.json',
 'str_2_2.json',
 'str_2_6.json',
 'str_3_6.json',
 'str_4_6.json',
 'str_5_6.json',
 'str_6_6.json',
 'str_dp.json',
 'str_ud.json',
 'vogue.json']

In [4]:
data = {}
for el in filenames:
    if '.json' in el:
        with open('stats/' + el, encoding='utf-8') as f:
            data[el[:-5]] = json.load(f)

In [5]:
n1 = ['width', 'width_no', 'depth', 'size', 'size_part', 'length']
n2 = ['kl', 'mean', 'pearson', 'p_val']
names = ['corpus', ]
for el1 in n1:
    for el2 in n2:
        names.append(el1 + '_' + el2)
names.extend(['max_d', 'max_l'])

In [6]:
data_pd = []
for el in data:
    new_el = [el, ]
    for el1 in n1:
        new_el.extend(data[el][el1])
    new_el.extend(data[el]['min_max'])
    data_pd.append(new_el)

In [7]:
df = pd.DataFrame(data_pd, columns=names)

In [8]:
df

,corpus,width_kl,width_mean,width_pearson,width_p_val,width_no_kl,width_no_mean,width_no_pearson,width_no_p_val,depth_kl,...,size_part_kl,size_part_mean,size_part_pearson,size_part_p_val,length_kl,length_mean,length_pearson,length_p_val,max_d,max_l
0,gen,0.000247,0.000122,0.999988,1.133183e-227,0.000426,0.000173,0.999931,4.800877e-191,0.000025,...,0.069500,0.002114,0.998598,6.906935e-127,0.000411,0.000057,0.999995,6.606864e-247,16,142
1,gorky,0.005192,0.000733,0.998765,1.364114e-129,0.008640,0.001010,0.996316,2.325992e-106,0.137089,...,0.076715,0.002250,0.997523,8.623717e-115,0.001191,0.000418,0.999321,2.565799e-142,20,133
2,gpt2,0.031234,0.001688,0.995065,3.771073e-100,0.049453,0.002072,0.985724,1.214525e-77,0.132099,...,0.115481,0.005375,0.993934,9.042487e-96,0.003617,0.000732,0.997918,1.732643e-118,16,96
3,gpt3,0.026273,0.001403,0.996769,3.825971e-109,0.040348,0.001751,0.988606,2.068551e-82,0.152324,...,0.092869,0.005250,0.994422,1.504718e-97,0.002300,0.000553,0.998596,7.235077e-127,20,69
4,news_dp,0.008386,0.000724,0.999078,8.094965e-136,0.016135,0.001369,0.992694,7.942845e-92,0.198919,...,0.061000,0.002167,0.998087,2.732584e-120,0.001490,0.000318,0.999509,3.258198e-149,21,311
5,science,0.007751,0.000724,0.999510,3.093207e-149,0.013288,0.001118,0.996252,5.421059e-106,0.079223,...,0.078041,0.002333,0.997699,2.319447e-116,0.000894,0.000269,0.999699,1.353143e-159,22,106
6,str_1_2,0.000290,0.000135,0.999970,1.053231e-208,0.000493,0.000226,0.999815,5.040652e-170,0.000065,...,0.056931,0.002833,0.998536,5.610618e-126,0.000040,0.000045,0.999991,3.521531e-233,22,163
7,str_1_6,0.001020,0.000243,0.999878,8.260082e-179,0.001907,0.000459,0.999317,3.384905e-142,0.000144,...,0.063828,0.004333,0.996520,1.444334e-107,0.000152,0.000109,0.999956,1.834460e-200,17,111
8,str_2_2,0.000302,0.000140,0.999969,9.569720e-208,0.000508,0.000229,0.999803,1.114352e-168,0.000073,...,0.065262,0.003083,0.997177,5.106834e-112,0.000047,0.000053,0.999989,2.117295e-229,21,122
9,str_2_6,0.000444,0.000117,0.999982,3.812086e-220,0.000878,0.000207,0.999856,2.613422e-175,0.000202,...,0.079783,0.004542,0.996291,3.230381e-106,0.000096,0.000059,0.999991,4.521575e-234,17,163
10,str_3_6,0.001198,0.000223,0.999934,7.684662e-192,0.001815,0.000354,0.999588,6.109358e-153,0.000187,...,0.057011,0.004250,0.996564,7.688392e-108,0.000046,0.000031,0.999998,1.146527e-263,22,78
11,str_4_6,0.000771,0.000190,0.999968,3.153137e-207,0.001441,0.000304,0.999788,4.722979e-167,0.000176,...,0.065738,0.004167,0.996610,3.977101e-108,0.000071,0.000061,0.999980,7.557004e-218,21,122
12,str_5_6,0.000755,0.000215,0.999895,5.109185e-182,0.001364,0.000377,0.999518,1.253601e-149,0.000071,...,0.045531,0.004083,0.997675,3.891833e-116,0.000065,0.000069,0.999982,2.136265e-219,18,114
13,str_6_6,0.003201,0.000485,0.999372,5.533496e-144,0.005678,0.000871,0.995849,8.020178e-104,0.000459,...,0.075691,0.004458,0.996348,1.528427e-106,0.000340,0.000161,0.999911,1.426007e-185,15,68
14,str_dp,0.009630,0.001215,0.997352,2.242384e-113,0.008059,0.000820,0.997780,4.052679e-117,0.143260,...,0.377243,0.007392,0.986963,1.464460e-79,0.018228,0.001471,0.989663,1.796109e-84,11,26
15,str_ud,0.000050,0.000051,0.999995,3.465318e-245,0.000119,0.000104,0.999969,3.461617e-208,0.000264,...,0.051592,0.001667,0.999030,9.855019e-135,0.000010,0.000014,1.000000,6.002620e-297,23,163
16,vogue,0.011740,0.001072,0.997204,3.195584e-112,0.019657,0.001283,0.996284,3.551382e-106,0.103754,...,0.072902,0.002292,0.997932,1.246072e-118,0.003039,0.000659,0.998168,3.351156e-121,18,107

In [9]:
df.to_csv('stats/metrics.csv', sep='\t', encoding='utf-8')

In [10]:
df['summ'] = df['width_kl'] + df['width_no_kl'] + df['depth_kl'] + df['size_kl'] + df['size_part_kl'] + df['length_kl']

In [11]:
df[['corpus', 'summ']].sort_values(by='summ')

     corpus      summ
12  str_5_6  0.050724
15   str_ud  0.058954
10  str_3_6  0.064370
6   str_1_2  0.064673
7   str_1_6  0.072061
11  str_4_6  0.073614
8   str_2_2  0.073944
0       gen  0.079601
9   str_2_6  0.088272
13  str_6_6  0.091820
5   science  0.189541
16    vogue  0.220889
1     gorky  0.239312
4   news_dp  0.295188
3      gpt3  0.321990
2      gpt2  0.342148
14   str_dp  0.604377

In [12]:
df[14:15][['width_kl', 'width_no_kl', 'depth_kl', 'size_kl', 'size_part_kl', 'length_kl']]

    width_kl  width_no_kl  depth_kl   size_kl  size_part_kl  length_kl
14   0.00963     0.008059   0.14326  0.047958      0.377243   0.018228

Он сделал что-то очень нехорошее с предложениями...

![title](2.png)

![title](1.png)

In [13]:
df['hmean'] = stats.hmean([df['width_kl'], df['width_no_kl'], df['depth_kl'], df['size_kl'], 
                             df['size_part_kl'], df['length_kl']])

In [14]:
df[['corpus', 'hmean']].sort_values(by='hmean')

     corpus     hmean
15   str_ud  0.000046
0       gen  0.000123
6   str_1_2  0.000130
8   str_2_2  0.000148
12  str_5_6  0.000189
10  str_3_6  0.000210
11  str_4_6  0.000272
9   str_2_6  0.000317
7   str_1_6  0.000395
13  str_6_6  0.001039
5   science  0.004153
1     gorky  0.004747
4   news_dp  0.006110
3      gpt3  0.009348
16    vogue  0.010160
2      gpt2  0.013563
14   str_dp  0.019153